version: "3"

volumes:
  state-management-postgres-data:
services:
  sample-postgres-database:
    image: postgres:14.1-alpine
    container_name: state-management-postgres
    volumes:
      - state-management-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: stateManagement
    ports:
      - "5432:5432"